import Head from 'next/head'
import { Lora } from 'next/font/google'
import Sidebar from '../../components/Sidebar'
import Widgets from '../../components/Widgets'
import Feed from '../../components/Feed'
import { getProviders, getSession, useSession } from 'next-auth/react'
import Login from '../../components/Login'
import Modal from '../../components/Modal'
import { modalState } from '../../atoms/modalAtom'
import { useRecoilState } from 'recoil'

const lora = Lora({ subsets: ['latin'] })

{
  /* <h1 className={`${lora.className} text-9xl text-[#443ce5]`}></h1> */
}

export default function Home({ trendingResults, followResults, providers }) {
  const { data: session } = useSession()
  const [isOpen, setIsOpen] = useRecoilState(modalState)

  if (!session) return <Login providers={providers} />

  return (
    <div className="">
      <Head>
        <title>Vibing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white min-h-screen flex max-w-[1500px] mx-auto">
        <Sidebar />
        <Feed />
        <Widgets trendingResults={trendingResults} followResults={followResults} />

        {isOpen && <Modal />}
      </main>
    </div>
  )
}

export async function getServerSideProps(context: any) {
  const trendingResults = []
  const followResults = []
  const providers = await getProviders()
  const session = await getSession(context)

  return {
    props: {
      trendingResults,
      followResults,
      providers,
      session,
    },
  }
}
